---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 1024

platforms:
- name: ubuntu-13.04
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  run_list:
  - recipe[apt]

- name: centos-6.5
- name: centos-5.10

suites:
- name: server-community
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::server]
  attributes:
    couchbase:
      server:
        password: "whatever"

- name: server-enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::server]
  attributes:
    couchbase:
      server:
        edition: "enterprise"
        password: "whatever"
        version: "2.1.0"

- name: moxi
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::moxi]
  attributes: {}

- name: client
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::client]
  attributes: {}
